### ISSUE TITLE
Volume Controls

### ISSUE THREAD

**Issue by BarnicleFiend** [NorthernMan54/homebridge-yamaha-zone-tv#17]
Is there a trick to getting the volume controls to show? 

I’ve got both zones showing as television accessories with inputs, power & remote + separate switches for main power and party mode. No volume controls though...

I’ve got a basic config with no errors showing in the log.

**Comment by NorthernMan54** [comment]
This is Apple's great idea for how a TV should be controlled, the volume controls are part of the remote app on your phone.

if you have a different approach, my other yahama plugin creates a Fan with the volume being fan speed.

**Comment by nitaybz** [comment]
Why not involving a fan as a feature to control the volume instead of having to get another plugin for that part?

**Comment by NorthernMan54** [comment]
@nitaybz That's what my other Yamaha plugin does "homebridge-yamaha-home".  I had built Yamaha-zone-tz to see how a TV accessory would work with my stereo, but I don't actually use it as I prefer the user experience of the "Fan" control more.

And to be perfectly honest I just Alexa for the interface these days, are rarely pull out the home app.

**Comment by nitaybz** [comment]
This plugin is great and feel more natural in control, and soon to have its own audio receiver icon if you set the proper category of the device. But you are most definitely right about the fan control which is essential, but I would just leave it for volume where 0 is mute and not turn off the machine, all of that can be part of one great plugin.

I'll try to invest in a big PR if you don't mind and don't have the time for it...
