### ISSUE TITLE
Current volume is not in sync with the receiver

### ISSUE THREAD

**Issue by nitaybz** [NorthernMan54/homebridge-yamaha-zone-tv#20]
I noticed that if I change the volume in the remote and than change it from the plugin, the plugin will remember its last state and not make the change relative to the current state of the receiver.

That could be easily fix by setting properly the get function of the volume characteristic to be updated with the current AVR state.

**Comment by NorthernMan54** [comment]
A better approach than implementing the get event is to create a status refresh function and have it fire regularly and update the current volume.  That way the Home app will change automatically without touching the app.

Personally I never use the remote, as the receiver is sitting in a cupboard
