### ISSUE TITLE
Issue with 0.1.19 and Inputs with Custom Names

### ISSUE THREAD

**Issue by moibensa** [NorthernMan54/homebridge-yamaha-zone-tv#22]
Great update overall. 
Having some issues with custom input names. Previously with 0.1.18 and before Inputs with custom names like ‘Apple TV’ could be set from the input wheel. With the recent version the zone names of the current zone are read correctly from the receiver but I cannot set the input to any custom named input. I can set it to Airplay or SERVER or AV5 but not to ‘Apple TV’

**Comment by NorthernMan54** [comment]
@nitaybz any thoughts?

**Comment by nitaybz** [comment]
I'll fix it...

**Comment by nitaybz** [comment]
please merge the latest fix

**Comment by NorthernMan54** [comment]
Published on NPM, please update and try again

**Comment by moibensa** [comment]
Working now. Thanks!
