### ISSUE TITLE
some inputs not detected

### ISSUE THREAD

**Issue by nickk024** [NorthernMan54/homebridge-yamaha-zone-tv#24]
Has been working well for what I need, but it doesn't seem to get any of the AV inputs that are available on my Yamaha RX-V573. It only gets the HDMI inputs, Airplay, NET RADIO, and TUNER. Is there any way to get one of the AV inputs to show up under my TV device?

**Comment by NorthernMan54** [comment]
Did you look under settings / inputs ?  With mine I can select which inputs I want to appear

**Comment by nickk024** [comment]
I did, unfortunately they do not show up there

**Comment by NorthernMan54** [comment]
In the Home app under settings for the receiver? 

![B6667EED-54C6-4BC8-9B9D-29493F6A7813](https://user-images.githubusercontent.com/19808920/91650595-8309e080-ea4f-11ea-9dbc-f3e06fd90a3d.png)
