### ISSUE TITLE
Question: Syntax for zone_controllers_only_for parameter

### ISSUE THREAD

**Issue by CooperCGN** [NorthernMan54/homebridge-yamaha-zone-tv#4]
Sorry to bother, but what is the syntax for the zone_controllers_only_for parameter if I just want the main zone to be exposed to HomeKit?
I assume it’s something like “zone_controllers_only_for”: main

**Comment by NorthernMan54** [comment]
I looked at the code, and I never implemented this function which I copied the over plugin over as a base.   I have since fixed this.  To find the name, when you run the code it will log the zone names “Adding TV Control for”.  Just use that/

                        if (this.zoneControllersOnlyFor == null || this.zoneControllersOnlyFor.includes(zoneName)) {
                          this.log("Adding TV Control for", zoneName);
